namespace Samples.Facade;

using Samples.Person.Get;

// ================================================================
//  CUSTOM EXTENSIONS ON GENERATED FACADE CLASSES
//
//  The Facade Generator creates group classes like MediatorPersons
//  with a public IMediator Mediator property. Because the class
//  is not sealed, you can extend it with your own methods using
//  C# 14's extension syntax.
//
//  This is powerful for composing multiple facade calls into
//  higher-level business operations — without modifying the
//  generated code.
//
//  The generated class looks like this:
//
//    public class MediatorPersons
//    {
//        public IMediator Mediator { get; }
//        public MediatorPersonsGet Get { get; }
//        // ...
//    }
//
//  You extend it just like any other type:
// ================================================================

/// <summary>
/// Custom extensions that compose multiple generated facade calls
/// into higher-level business operations.
/// </summary>
public static class CustomPersonsExtensions
{
  extension(MediatorPersons persons)
  {
    /// <summary>
    /// Creates a new person and immediately verifies they exist by looking them up.
    ///
    /// This demonstrates how you can compose generated facade methods
    /// into a single, reusable operation:
    ///
    ///   1. mediator.Persons.Create(email)              — generated
    ///   2. mediator.Persons.Get.ByEmail(email)         — generated
    ///   3. mediator.Persons.CreateAndVerify(email, ...) — YOUR extension
    ///
    /// The generated facade gives you the building blocks,
    /// your extensions give you the business workflows.
    /// </summary>
    public async Task<PersonResult?> CreateAndVerify(
      string email,
      string firstName,
      string lastName)
    {
      // Step 1: Create the person via the generated facade.
      // Note: we access the generated extension methods on 'persons' directly.
      await persons.Create(email, configure: cmd =>
      {
        cmd.FirstName = firstName;
        cmd.LastName = lastName;
      });

      // Step 2: Verify by looking up the person via another generated facade method.
      // 'persons.Get' is a nested group — also generated, also extensible.
      return await persons.Get.ByEmail(email);
    }
  }
}

/// <summary>
/// You can also extend nested groups like MediatorPersonsGet.
/// </summary>
public static class CustomPersonsGetExtensions
{
  extension(MediatorPersonsGet get)
  {
    /// <summary>
    /// Searches for a person by name, scoped to a specific city.
    ///
    /// Demonstrates extending a nested group (mediator.Persons.Get.*)
    /// with a convenience method that pre-fills parameters.
    ///
    /// Usage: mediator.Persons.Get.ByNameInCity("John", "Berlin")
    /// </summary>
    public async Task<PersonResult> ByNameInCity(string name, string city)
    {
      // Delegates to the generated ByName method, pre-filling the city parameter.
      return await get.ByName(name, city: city);
    }
  }
}
