namespace MediatR.Extensions.FluentBuilder;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using MediatR.Extensions.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

/// <summary>
/// Source generator for the Fluent Builder pattern for MediatR requests.
/// </summary>
[Generator]
public sealed class MediatorFluentBuilderGenerator : IIncrementalGenerator
{
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    var projectNamespaceProvider = context.CompilationProvider
      .Select(static (compilation, _) => compilation.Assembly.Name);

    // Local candidates from the current project
    var localCandidates = context.SyntaxProvider
      .CreateSyntaxProvider(
        predicate: static (node, _) => MediatorRequestDiscovery.IsCandidateClass(node),
        transform: static (ctx, _) => MediatorRequestDiscovery.GetSemanticTarget(ctx))
      .Where(static m => m is not null)
      .Select(static (m, _) => m!);

    // Search referenced assemblies
    var referencedCandidates = context.CompilationProvider
      .SelectMany(static (compilation, _) => MediatorRequestDiscovery.GetRequestInfosFromReferences(compilation));

    // Combine both sources
    var allCandidates = localCandidates.Collect()
      .Combine(referencedCandidates.Collect())
      .SelectMany((pair, _) =>
      {
        var local = pair.Left;
        var referenced = pair.Right;
        return local.Concat(referenced);
      });

    var requestInfosWithProject = allCandidates
      .Combine(projectNamespaceProvider);

    // Generate fluent builder for requests with GenerateFluentBuilder attribute
    context.RegisterSourceOutput(
      requestInfosWithProject,
      static (spc, tuple) =>
      {
        var info = tuple.Left;
        var projectNamespace = tuple.Right;

        if (info.GenerateFluentBuilder)
        {
          GenerateFluentBuilder(spc, info, projectNamespace);
        }
      });

    // Generate build namespaces (MediatorBuildNamespace and group build namespaces)
    var collected = allCandidates.Collect();
    var collectedWithProject = collected.Combine(projectNamespaceProvider);

    context.RegisterSourceOutput(
      collectedWithProject,
      static (spc, pair) =>
      {
        var infos = pair.Left;
        var projectNamespace = pair.Right;
        GenerateBuildNamespaces(spc, infos, projectNamespace);
      });
  }

  // ------------------------------------------------------------
  //  Build Namespace Generation
  // ------------------------------------------------------------

  private static void GenerateBuildNamespaces(
    SourceProductionContext context,
    ImmutableArray<MediatorRequestInfo> infos,
    string projectNamespace)
  {
    if (infos.IsDefaultOrEmpty)
    {
      return;
    }

    // Collect all requests with FluentBuilder
    var builderRequests = infos
      .Where(i => i.GenerateFluentBuilder)
      .ToList();

    if (builderRequests.Count == 0)
    {
      return;
    }

    // Collect all unique group paths
    var groupPaths = new HashSet<string>();
    foreach (var request in builderRequests)
    {
      if (!string.IsNullOrEmpty(request.GroupName))
      {
        // Add all segments (e.g. "Persons.Admin" -> ["Persons", "Persons.Admin"])
        var segments = request.GroupName.Split('.');
        for (int i = 0; i < segments.Length; i++)
        {
          var path = string.Join(".", segments.Take(i + 1));
          groupPaths.Add(path);
        }
      }
    }

    // Generate MediatorBuildNamespace (root)
    GenerateMediatorBuildNamespace(context, projectNamespace);

    // Generate group build namespaces
    foreach (var groupPath in groupPaths.OrderBy(p => p))
    {
      GenerateGroupBuildNamespace(context, projectNamespace, groupPath);
    }
  }

  private static void GenerateMediatorBuildNamespace(
    SourceProductionContext context,
    string projectNamespace)
  {
    var source = $$"""
                   // <auto-generated />
                   #nullable enable

                   namespace {{projectNamespace}};

                   /// <summary>
                   /// Build namespace for creating fluent builder instances.
                   /// Access via: mediator.Build
                   /// </summary>
                   public sealed class MediatorBuildNamespace
                   {
                       internal global::MediatR.IMediator Mediator { get; }

                       internal MediatorBuildNamespace(global::MediatR.IMediator mediator)
                       {
                           this.Mediator = mediator ?? throw new global::System.ArgumentNullException(nameof(mediator));
                       }
                   }

                   /// <summary>
                   /// Extension: mediator.Build
                   /// </summary>
                   public static class MediatorBuildExtensions
                   {
                       extension(global::MediatR.IMediator mediator)
                       {
                           public MediatorBuildNamespace Build => new(mediator);
                       }
                   }
                   """;

    context.AddSource("MediatorBuildNamespace.g.cs", source);
  }

  private static void GenerateGroupBuildNamespace(
    SourceProductionContext context,
    string projectNamespace,
    string groupPath)
  {
    var segments = groupPath.Split('.');
    var lastSegment = segments[segments.Length - 1];
    var className = $"{lastSegment}BuildNamespace";

    // Determine parent
    string parentClassName;
    if (segments.Length == 1)
    {
      // Root-level: parent is MediatorBuildNamespace
      parentClassName = "MediatorBuildNamespace";
    }
    else
    {
      // Nested: parent is the previous level
      var parentSegment = segments[segments.Length - 2];
      parentClassName = $"{parentSegment}BuildNamespace";
    }

    var source = $$"""
                   // <auto-generated />
                   #nullable enable

                   namespace {{projectNamespace}};

                   /// <summary>
                   /// Build namespace for {{groupPath}} group.
                   /// Access via: mediator.Build.{{groupPath}}
                   /// </summary>
                   public sealed class {{className}}
                   {
                       internal global::MediatR.IMediator Mediator { get; }

                       internal {{className}}(global::MediatR.IMediator mediator)
                       {
                           this.Mediator = mediator ?? throw new global::System.ArgumentNullException(nameof(mediator));
                       }
                   }

                   /// <summary>
                   /// Extension: {{(segments.Length == 1 ? "mediator.Build." + lastSegment : parentClassName + "." + lastSegment)}}
                   /// </summary>
                   public static class {{className}}Extensions
                   {
                       extension({{parentClassName}} parent)
                       {
                           public {{className}} {{lastSegment}} => new(parent.Mediator);
                       }
                   }
                   """;

    var hintName = $"MediatorBuildNamespace.{className}.g.cs";
    context.AddSource(hintName, source);
  }

  /// <summary>
  /// Generates the class name for build namespaces.
  /// Format: [LastGroupSegment]BuildNamespace (e.g. "PersonsBuildNamespace", "AdminBuildNamespace")
  /// For root, "MediatorBuildNamespace" is used.
  /// </summary>
  private static string GetBuildNamespaceClassName(string? groupPath)
  {
    if (string.IsNullOrEmpty(groupPath))
    {
      return "MediatorBuildNamespace";
    }

    var segments = groupPath.Split('.');
    var lastSegment = segments[segments.Length - 1];
    return $"{lastSegment}BuildNamespace";
  }

  // ------------------------------------------------------------
  //  Fluent Builder Generation
  // ------------------------------------------------------------

  private static void GenerateFluentBuilder(SourceProductionContext context, MediatorRequestInfo info,
    string projectNamespace)
  {
    var requestType = info.RequestType;
    var responseType = info.ResponseType;
    var fullRequestTypeName = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    // Collect all public constructors
    var allConstructors = MediatorRequestDiscovery.GetAllPublicConstructors(requestType);

    // Collect all properties with BuilderMethodAttribute
    var propertyInfos = requestType.GetMembers()
      .OfType<IPropertySymbol>()
      .Where(p => p.DeclaredAccessibility == Accessibility.Public && p.SetMethod is not null)
      .Select(p => new
      {
        Property = p,
        Attribute = p.GetAttributes().FirstOrDefault(a =>
          a.AttributeClass?.Name is "BuilderMethodAttribute" or "BuilderMethod")
      })
      .Where(x => x.Attribute is not null)
      .Select(x => new BuilderPropertyInfo(
        x.Property,
        GetBuilderMethodName(x.Attribute!),
        GetBuilderParameterName(x.Attribute!, x.Property),
        GetBuilderOrder(x.Attribute!)
      ))
      .ToList();

    if (propertyInfos.Count == 0)
    {
      // No properties with BuilderMethodAttribute found
      return;
    }

    // Group by method name
    var methodGroups = propertyInfos
      .GroupBy(p => p.MethodName)
      .OrderBy(g => g.Key)
      .ToList();

    // Builder class name: [OriginalClassName]Builder
    var builderClassName = $"{requestType.Name}Builder";
    // Method name is the full class name
    var methodName = requestType.Name;

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine($"namespace {projectNamespace};");
    sb.AppendLine();

    // Builder class
    sb.AppendLine($"public sealed class {builderClassName}");
    sb.AppendLine("{");
    sb.AppendLine($"  private readonly {fullRequestTypeName} request;");
    sb.AppendLine("  private readonly global::MediatR.IMediator mediator;");
    sb.AppendLine();

    // Generate a builder constructor for each public constructor
    foreach (var ctorInfo in allConstructors)
    {
      if (ctorInfo.Parameters.IsDefaultOrEmpty)
      {
        sb.AppendLine($"  internal {builderClassName}(global::MediatR.IMediator mediator)");
        sb.AppendLine("  {");
        sb.AppendLine(
          "    this.mediator = mediator ?? throw new global::System.ArgumentNullException(nameof(mediator));");
        sb.AppendLine($"    this.request = new {fullRequestTypeName}();");
        sb.AppendLine("  }");
      }
      else
      {
        var constructorParams = string.Join(", ", ctorInfo.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
        var constructorArgs = string.Join(", ", ctorInfo.Parameters.Select(p => p.Name));

        sb.AppendLine($"  internal {builderClassName}(global::MediatR.IMediator mediator, {constructorParams})");
        sb.AppendLine("  {");
        sb.AppendLine(
          "    this.mediator = mediator ?? throw new global::System.ArgumentNullException(nameof(mediator));");
        sb.AppendLine($"    this.request = new {fullRequestTypeName}({constructorArgs});");
        sb.AppendLine("  }");
      }

      sb.AppendLine();
    }

    // Generate builder methods
    foreach (var group in methodGroups)
    {
      var methodNameForGroup = group.Key;
      var parameters = group.OrderBy(p => p.Order).ToList();

      // Build parameter list
      var paramList = string.Join(", ", parameters.Select(p =>
      {
        var paramType = p.Property.Type.ToDisplayString(MediatorRequestDiscovery.NullableFullyQualifiedFormat);
        return $"{paramType} {p.ParameterName}";
      }));

      sb.AppendLine($"  public {builderClassName} {methodNameForGroup}({paramList})");
      sb.AppendLine("  {");

      // Set each property
      foreach (var param in parameters)
      {
        sb.AppendLine($"    this.request.{param.Property.Name} = {param.ParameterName};");
      }

      sb.AppendLine("    return this;");
      sb.AppendLine("  }");
      sb.AppendLine();
    }

    // Build method: returns the constructed request
    sb.AppendLine($"  public {fullRequestTypeName} Build()");
    sb.AppendLine("  {");
    sb.AppendLine("    return this.request;");
    sb.AppendLine("  }");
    sb.AppendLine();

    // Send method: sends the request directly via MediatR
    if (responseType is not null)
    {
      var fullResponseTypeName = responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
      sb.AppendLine(
        $"  public global::System.Threading.Tasks.Task<{fullResponseTypeName}> Send(global::System.Threading.CancellationToken cancellationToken = default)");
      sb.AppendLine("  {");
      sb.AppendLine("    return this.mediator.Send(this.request, cancellationToken);");
      sb.AppendLine("  }");
    }
    else
    {
      sb.AppendLine(
        "  public global::System.Threading.Tasks.Task Send(global::System.Threading.CancellationToken cancellationToken = default)");
      sb.AppendLine("  {");
      sb.AppendLine("    return this.mediator.Send(this.request, cancellationToken);");
      sb.AppendLine("  }");
    }

    sb.AppendLine("}");
    sb.AppendLine();

    // Generate extension methods on build namespace classes
    var buildNamespaceClassName = GetBuildNamespaceClassName(info.GroupName);

    sb.AppendLine($"public static class {builderClassName}Extensions");
    sb.AppendLine("{");
    sb.AppendLine($"  extension({buildNamespaceClassName} build)");
    sb.AppendLine("  {");

    foreach (var ctorInfo in allConstructors)
    {
      if (ctorInfo.Parameters.IsDefaultOrEmpty)
      {
        sb.AppendLine($"    public {builderClassName} {methodName}()");
        sb.AppendLine("    {");
        sb.AppendLine($"      return new {builderClassName}(build.Mediator);");
        sb.AppendLine("    }");
      }
      else
      {
        var constructorParams = string.Join(", ", ctorInfo.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
        var constructorArgs = string.Join(", ", ctorInfo.Parameters.Select(p => p.Name));

        sb.AppendLine($"    public {builderClassName} {methodName}({constructorParams})");
        sb.AppendLine("    {");
        sb.AppendLine($"      return new {builderClassName}(build.Mediator, {constructorArgs});");
        sb.AppendLine("    }");
      }

      sb.AppendLine();
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");

    var hintName = $"MediatR.FluentBuilder.{requestType.Name}.g.cs";
    context.AddSource(hintName, sb.ToString());
  }

  private static string GetBuilderMethodName(AttributeData attribute)
  {
    if (attribute.ConstructorArguments.Length > 0)
    {
      return attribute.ConstructorArguments[0].Value as string ?? "With";
    }

    return "With";
  }

  private static string GetBuilderParameterName(AttributeData attribute, IPropertySymbol property)
  {
    // Look for ParameterName in named arguments
    var parameterNameArg = attribute.NamedArguments.FirstOrDefault(a => a.Key == "ParameterName");
    if (parameterNameArg.Value.Value is string paramName && !string.IsNullOrEmpty(paramName))
    {
      return paramName;
    }

    // Fallback: property name in camelCase
    var propertyName = property.Name;
    return char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
  }

  private static int GetBuilderOrder(AttributeData attribute)
  {
    var orderArg = attribute.NamedArguments.FirstOrDefault(a => a.Key == "Order");
    if (orderArg.Value.Value is int order)
    {
      return order;
    }

    return 0;
  }

  private record BuilderPropertyInfo(
    IPropertySymbol Property,
    string MethodName,
    string ParameterName,
    int Order);
}
